import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import type { LaneManifest } from './manifest.js';

/** Gitignored by the existing `.env.*` rule. Holds live credentials. */
export const LANE_ENV_FILE = '.env.lane';

/** The developer's own env file, which the lane database is derived from. */
export const ROOT_ENV_FILE = '.env';

/**
 * The root `.env`, parsed. `lane up` derives the lane database from
 * `DATABASE_URL`, which lives in this file and which a plain shell has never
 * exported — every other entry point in the repo reads it, so the lane CLI
 * must too. Returns empty when there is no file: the caller reports the
 * missing variable, which is the more useful error.
 *
 * Hand-parsed rather than delegated to `dotenv`, which this package does
 * depend on and which `context.ts` uses. `lane up` is the command that runs
 * `pnpm install`, and on a fresh worktree `packages/preflight/node_modules`
 * does not exist yet — `tsx` resolves from the repository root, but a package
 * dependency does not resolve at all until the install this function is
 * needed to reach.
 */
export function readRootEnv(worktreePath: string): Record<string, string> {
  const file = path.join(worktreePath, ROOT_ENV_FILE);

  return existsSync(file) ? parseLaneEnv(readFileSync(file, 'utf8')) : {};
}

export function renderLaneEnv(manifest: LaneManifest, databaseUrl: string): string {
  return [
    `# Lane ${manifest.ticket}. Generated by \`pnpm lane:up\`; do not edit or commit.`,
    `PORT=${manifest.apiPort}`,
    `WEB_PORT=${manifest.webPort}`,
    `NEXT_PUBLIC_API_URL=http://localhost:${manifest.apiPort}`,
    /*
     * The API derives its CORS allowlist from `WEB_URL`. Without this line a
     * lane inherits the root `.env`'s `http://localhost:3000`, so the lane's
     * own web origin is refused and every client-side call fails as
     * `net::ERR_FAILED` — which makes browser verification of a lane
     * impossible, and looks like the change under test being broken.
     */
    `WEB_URL=http://localhost:${manifest.webPort}`,
    `DATABASE_URL=${databaseUrl}`,
    /*
     * DATABASE_URL_UNPOOLED and NEON_BRANCH are deliberately absent. They
     * describe a Neon deployment; the env registry marks them optional for
     * `local`, and setting them against the Docker container fails the gate.
     */
    '',
  ].join('\n');
}

/** `VALUE`, `"VALUE"` and `'VALUE'` all mean the same thing to dotenv. */
function unquote(value: string): string {
  const quote = value[0];

  return (quote === '"' || quote === "'") && value.endsWith(quote) && value.length > 1
    ? value.slice(1, -1)
    : value;
}

export function parseLaneEnv(contents: string): Record<string, string> {
  const values: Record<string, string> = {};

  for (const line of contents.split('\n')) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const separator = trimmed.indexOf('=');

    if (separator === -1) {
      continue;
    }

    values[trimmed.slice(0, separator)] = unquote(trimmed.slice(separator + 1));
  }

  return values;
}

/**
 * The lane file WINS over an inherited value. This is the opposite of dotenv's
 * precedence, deliberately: the file exists to override, and a lane launched
 * from a shell that had already sourced the root `.env` would otherwise bind
 * the shared ports and silently lose its isolation.
 */
export function childEnv(base: NodeJS.ProcessEnv, contents: string): NodeJS.ProcessEnv {
  return { ...base, ...parseLaneEnv(contents) };
}
