import { parse } from 'dotenv';
import type { LaneManifest } from './manifest.js';

/** Gitignored by the existing `.env.*` rule. Holds live credentials. */
export const LANE_ENV_FILE = '.env.lane';

export function renderLaneEnv(manifest: LaneManifest, databaseUrl: string): string {
  return [
    `# Lane ${manifest.ticket}. Generated by \`pnpm lane:up\`; do not edit or commit.`,
    `PORT=${manifest.apiPort}`,
    `WEB_PORT=${manifest.webPort}`,
    `NEXT_PUBLIC_API_URL=http://localhost:${manifest.apiPort}`,
    /*
     * **The server-side twin, and it is a different variable.** `api-client.ts`
     * reads `process.env.API_URL` for every Server Component fetch, while
     * `NEXT_PUBLIC_API_URL` above is inlined into the browser bundle. Writing
     * only the public one leaves the root `.env`'s `API_URL=http://localhost:4000`
     * in force, so a lane's *pages* silently render against the first lane's
     * API — or against a checkout that has none of this lane's data.
     *
     * That is worse than the CORS failure below, because it does not look like
     * a failure. Found on 2026-09-07 in lane 432, where every `/admin/*` route
     * rendered the 500 page: `admin/layout.tsx` awaits a server-side admin read
     * before any child renders, and :4000 answered 500 for a token minted
     * against this lane. Five UI acceptance items were unverifiable and the
     * cause read as a defect in the change under test.
     */
    `API_URL=http://localhost:${manifest.apiPort}`,
    /*
     * The API derives its CORS allowlist from `WEB_URL`. Without this line a
     * lane inherits the root `.env`'s `http://localhost:3000`, so the lane's
     * own web origin is refused and every client-side call fails as
     * `net::ERR_FAILED` — which makes browser verification of a lane
     * impossible, and looks like the change under test being broken.
     */
    `WEB_URL=http://localhost:${manifest.webPort}`,
    `DATABASE_URL=${databaseUrl}`,
    /*
     * DATABASE_URL_UNPOOLED and NEON_BRANCH are deliberately absent. They
     * describe a Neon deployment; the env registry marks them optional for
     * `local`, and setting them against the Docker container fails the gate.
     */
    '',
  ].join('\n');
}

/**
 * Reads any env file this package touches — the generated lane file and the
 * hand-written repository `.env` alike.
 *
 * `dotenv` rather than a hand-rolled splitter, so there is one reader in the
 * package. The splitter this replaced did not strip quotes, which is invisible
 * on the generated file (it is written unquoted) and broke on the repository
 * `.env`, whose `DATABASE_URL="postgresql://…"` came back with the quotes
 * attached and was rejected by `new URL`.
 */
export function parseLaneEnv(contents: string): Record<string, string> {
  return parse(contents);
}

/**
 * The lane file WINS over an inherited value. This is the opposite of dotenv's
 * precedence, deliberately: the file exists to override, and a lane launched
 * from a shell that had already sourced the root `.env` would otherwise bind
 * the shared ports and silently lose its isolation.
 */
export function childEnv(base: NodeJS.ProcessEnv, contents: string): NodeJS.ProcessEnv {
  return { ...base, ...parseLaneEnv(contents) };
}
