import { beforeAll, describe, expect, it } from 'vitest';
import { normaliseForMatch, US_STATE_CODES } from '@vendor-marketplace/shared';
import { US_CITY_NAME_MAX_LENGTH } from './schema/us-cities.js';
import { usCityRows } from './us-cities.js';

/**
 * The committed dataset's own invariants, asserted without a database.
 *
 * It is generated by a script that reaches the network, so nothing in CI
 * re-derives it — which makes the file itself the thing to check. Every failure
 * here is a refresh that went wrong, and each one would otherwise surface as a
 * seed that dies mid-insert or a city a customer can see and cannot find.
 */
describe('usCityRows', () => {
  // `usCityRows` is async so the 612KB dataset can be a dynamic import — see
  // its own note. Resolved once for the file rather than per case.
  let rows: Awaited<ReturnType<typeof usCityRows>> = [];

  beforeAll(async () => {
    rows = await usCityRows();
  });

  it('covers the country at the scale the sources describe', () => {
    // ~35,600 places today. The bound is loose on purpose: this is a guard
    // against a truncated download, not a pin on a number that legitimately
    // moves when the Census re-runs.
    expect(rows.length).toBeGreaterThan(30_000);
    expect(rows.length).toBeLessThan(45_000);
  });

  it('names only states the closed enum admits', () => {
    const allowed = new Set<string>(US_STATE_CODES);
    const strays = [...new Set(rows.map((row) => row.state))].filter(
      (state) => !allowed.has(state),
    );

    // A territory or a stray `PR` would be inserted against a `us_state` enum
    // that has no such value, and the seed would fail with a type error rather
    // than a message about the data.
    expect(strays).toEqual([]);
    expect(new Set(rows.map((row) => row.state)).size).toBe(US_STATE_CODES.length);
  });

  it('fits every name in the column it is inserted into', () => {
    // Read off the schema rather than restated, so widening the column cannot
    // leave this asserting the old bound.
    expect(rows.filter((row) => row.name.length > US_CITY_NAME_MAX_LENGTH)).toEqual([]);
  });

  it('carries no blank name and no negative population', () => {
    expect(rows.filter((row) => row.name.trim() === '')).toEqual([]);
    expect(rows.filter((row) => row.population < 0)).toEqual([]);
  });

  it('holds each (name, state) pair once, because the pair is the primary key', () => {
    const seen = new Set<string>();
    const duplicates: string[] = [];

    for (const row of rows) {
      const key = `${row.name}|${row.state}`;
      if (seen.has(key)) {
        duplicates.push(key);
      }
      seen.add(key);
    }

    expect(duplicates).toEqual([]);
  });

  it('normalises every search name with the shared function the API matches on', () => {
    // The one invariant that fails *silently*: a `search_name` written by a
    // different rule than the API applies to the typed query is a city that is
    // in the table and unreachable from the field.
    const wrong = rows.filter((row) => row.searchName !== normaliseForMatch(row.name));

    expect(wrong).toEqual([]);
  });

  it('includes the places the ranking rules were written about', () => {
    const find = (name: string, state: string) =>
      rows.find((row) => row.name === name && row.state === state);

    for (const [name, state] of [
      ['Austin', 'TX'],
      ['Portland', 'OR'],
      ['Portland', 'ME'],
      ['Springfield', 'IL'],
      ['New York', 'NY'],
      // Both census-designated places, and both the reason the dataset takes
      // its population from GeoNames rather than the Census series: that series
      // covers incorporated places only, and would rank these two last.
      ['Arlington', 'VA'],
      ['Honolulu', 'HI'],
    ] as const) {
      expect(find(name, state), `${name}, ${state}`).toBeDefined();
    }

    expect(find('Portland', 'OR')!.population).toBeGreaterThan(find('Portland', 'ME')!.population);
    expect(find('Arlington', 'VA')!.population).toBeGreaterThan(0);
  });
});
