import { registrySchemaShape } from '@vendorhub/shared/env';
import { z } from 'zod';

/**
 * Capabilities apps/web reads. Stripe joins this list in ticket #9, Sentry in
 * #15; until then their absence must not fail a build.
 */
const WEB_CAPABILITIES = ['core', 'auth'] as const;

/**
 * Build-time validation always uses the local target. `next build` sets
 * `NODE_ENV=production` for every build, including a local one, so it cannot
 * distinguish a release from `pnpm build` on a laptop — the stricter production
 * value set is checked by `pnpm preflight --env production` instead.
 */
const envSchema = z.object(
  registrySchemaShape({ consumer: 'web', capabilities: WEB_CAPABILITIES }),
);

export type WebEnv = z.infer<typeof envSchema>;

/**
 * Every `NEXT_PUBLIC_*` value the browser bundle uses, written out as literal
 * `process.env.X` references.
 *
 * Next.js inlines these at build time only when it can see the property access
 * statically, so this map cannot be generated by looping over the registry.
 * `env.test.ts` asserts it covers every browser-facing row instead, which is
 * the same drift guarantee by a different route.
 */
const PUBLIC_VALUES = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL:
    process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL,
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL:
    process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL,
} as const satisfies Record<string, string | undefined>;

export type PublicEnvKey = keyof typeof PUBLIC_VALUES;

export function publicEnvKeys(): PublicEnvKey[] {
  return Object.keys(PUBLIC_VALUES) as PublicEnvKey[];
}

/**
 * Throws rather than returning `undefined`: a missing public value renders as
 * the string "undefined" in the UI, which is far harder to trace back than an
 * error at the point of use.
 */
export function requirePublicValue(key: PublicEnvKey, value: string | undefined): string {
  if (!value) {
    throw new Error(`${key} is not set. Run \`pnpm preflight\` for the fix.`);
  }

  return value;
}

/** Reads a browser-facing value that the build inlined. */
export function publicEnv(key: PublicEnvKey): string {
  return requirePublicValue(key, PUBLIC_VALUES[key]);
}

/**
 * Validates every variable apps/web reads. Called from `next.config.ts`, where
 * the full `process.env` is still available — after the build, only the inlined
 * `NEXT_PUBLIC_*` values survive.
 */
export function assertWebEnv(source: NodeJS.ProcessEnv = process.env): WebEnv {
  const result = envSchema.safeParse(source);

  if (!result.success) {
    const problems = result.error.issues
      .map((issue) => `${issue.path.join('.')}: ${issue.message}`)
      .join('\n  ');

    throw new Error(
      `Invalid web environment configuration:\n  ${problems}\n\nRun \`pnpm preflight\` for the fix for each one.`,
    );
  }

  return result.data;
}
