/**
 * The browser-facing half of the environment, and nothing else.
 *
 * Deliberately a leaf: it imports neither `zod` nor the env registry, because
 * client components read from here. `config/env.ts` builds two Zod schemas over
 * the whole registry at module scope — correct for a build-time gate, and dead
 * weight in every client chunk if a `'use client'` hook can reach it. Keeping
 * the two apart is what lets `use-api`, `use-event-stream` and checkout import
 * one string without pulling the validation table into the bundle.
 *
 * `env.test.ts` pins these values against the registry, so the separation costs
 * no drift guarantee.
 */

/**
 * Every `NEXT_PUBLIC_*` value the browser bundle uses, written out as literal
 * `process.env.X` references.
 *
 * Next.js inlines these at build time only when it can see the property access
 * statically, so this map cannot be generated by looping over the registry.
 * `env.test.ts` asserts it covers every browser-facing row instead, which is
 * the same drift guarantee by a different route.
 */
const PUBLIC_VALUES = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL:
    process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL,
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL:
    process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL,
  NEXT_PUBLIC_S3_PUBLIC_URL: process.env.NEXT_PUBLIC_S3_PUBLIC_URL,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
} as const satisfies Record<string, string | undefined>;

export type PublicEnvKey = keyof typeof PUBLIC_VALUES;

export function publicEnvKeys(): PublicEnvKey[] {
  return Object.keys(PUBLIC_VALUES) as PublicEnvKey[];
}

/**
 * Throws rather than returning `undefined`: a missing public value renders as
 * the string "undefined" in the UI, which is far harder to trace back than an
 * error at the point of use.
 */
export function requirePublicValue(key: PublicEnvKey, value: string | undefined): string {
  if (!value) {
    throw new Error(`${key} is not set. Run \`pnpm preflight\` for the fix.`);
  }

  return value;
}

/** Reads a browser-facing value that the build inlined. */
export function publicEnv(key: PublicEnvKey): string {
  return requirePublicValue(key, PUBLIC_VALUES[key]);
}

/**
 * The development fallbacks, restated here rather than read from the registry
 * because reading them would import the registry into the browser bundle — the
 * thing this module exists to avoid. `env.test.ts` asserts each against its
 * registry row, so the copy cannot drift silently.
 */
export const LOCAL_WEB_ORIGIN = 'http://localhost:3000';
export const LOCAL_API_ORIGIN = 'http://localhost:4000';

/**
 * The API origin every call in this app is built on.
 *
 * One fallback, in one place. `api-client`, `use-api` and `use-event-stream`
 * each carried their own `?? 'http://localhost:4000'`, so the development
 * default was written three times and could be fixed in two of them.
 *
 * The literal is unreachable in a deployed bundle and that is the point:
 * `assertWebEnv` refuses to build one whose `NEXT_PUBLIC_API_URL` is absent, so
 * this can only resolve to localhost on a laptop. Before that gate existed, a
 * Vercel build with the variable unset baked localhost in, and every browser
 * call went to the visitor's own machine while every server-side loader dialled
 * its own container and hit `ECONNREFUSED`.
 *
 * @param serverFallback a private origin the browser bundle never sees, used
 *   only by server-side callers that may reach the API off its public host.
 */
export function apiOrigin(serverFallback?: string): string {
  return PUBLIC_VALUES.NEXT_PUBLIC_API_URL ?? serverFallback ?? LOCAL_API_ORIGIN;
}
